name: Dummy Check

on:
  pull_request:
    types: [opened, synchronize]
  merge_group:

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Run dummy check
        run: echo "This is a dummy check"
