# Validate commit messages in pull requests

name: Validate Commit Messages

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main   # 👈 add this

      
jobs:
  validate-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Get commit messages in the PR
        id: commits
        run: |
          echo "Getting commits in PR..."
          commits=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "${{ github.api_url }}/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/commits" \
            | jq -r '.[].commit.message | split("\n")[0]')
          echo "$commits" > commit_messages.txt

      - name: Validate commit messages contain Jira ticket
        run: |
          echo "Validating commit messages..."
          error=0
          while IFS= read -r line; do
            
            
            if [[ "$line" =~ ^Merge ]]; then
              echo "ℹ️  Skipping auto-generated commit: $line"
              continue
            fi

            
            if [[ "$line" =~ ^LGA-([1-9][0-9]?|100):\ .+ ]]; then
              echo "✅ Valid: $line"
            else
              echo "❌ Invalid commit message: $line"
              error=1
            fi
          done < commit_messages.txt

          if [ $error -ne 0 ]; then
            echo "✖ One or more commit messages are invalid."
            exit 1
          else
            echo "✔ All commit messages are valid."
          fi
